---
title: "p8105_hw_nkr2121"
author: "Nihaal Rahman"
output: github_document
---

```{r, echo = FALSE, message = FALSE}
library(tidyverse)
```

## Problem 1

Let's begin by loading in pols_month data set and cleaning it up. 

```{r}
pols_month <- read_csv("~/Documents/Columbia/Semester 3/Data1/fivethirtyeight_datasets/pols-month.csv") |> 
  separate(mon, into = c("year", "month", "day"), sep = '-') |> 
  mutate(month = month.name[as.numeric(month)],
         president = case_when(
           as.numeric(prez_gop) > 0 ~ "gop",
           as.numeric(prez_dem) > 0 ~ "dem"
         )) |> 
  select(-c("prez_dem", "prez_gop", "day"))
```

Now moving on to the snp data set.  

```{r}
snp <- read_csv("~/Documents/Columbia/Semester 3/Data1/fivethirtyeight_datasets/snp.csv") |> 
  separate(date, into = c("month", "year", "day"), sep = '/') |> 
  mutate(month = month.name[as.numeric(month)]) |> 
  arrange("year", "month") |> 
  select(c("year", "month", "close"))
```

Now moving onto the unemployment data set. 

```{r}
unemployment <- read_csv("~/Documents/Columbia/Semester 3/Data1/fivethirtyeight_datasets/unemployment.csv") |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = c("jan","feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"),
    names_to = "month",
    values_to = "unemployment_rate") |> 
  mutate(month = case_match(
    month,
    "jan" ~ "January",
    "feb" ~ "February",
    "mar" ~ "March",
    "apr" ~ "April",
    "may" ~ "May",
    "jun" ~ "June",
    "jul" ~ "July",
    "aug" ~ "August",
    "sep" ~ "September",
    "oct" ~ "October",
    "nov" ~ "November",
    "dec" ~ "December"
    ))
```


